# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Vogue"
# license = "MIT"
# licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://kolesnichenko.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = "Andrey S. Kolesnichenko"
  homepage = "http://kolsenichenko.com/"

